<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>Ninefold.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Ninefold/Runtime/Core/**/*.cs" />
  </ItemGroup>
</Project>
